name: sync-submodule

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: update submodules
        run: |
          git submodule update --init --recursive
          
      - name: Commit & push changes
        run: |
          git config --global user.email "captain_jainesh@yahoo.com"
          git config --global user.name "Jainesh Captain"
          git commit -m "Update submodules"
          git push
